{% set version = "1.2-24" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-partykit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/partykit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/partykit/partykit_{{ version }}.tar.gz
  sha256: 40c06b75458f100f3e203fb47f80d5be6f632628bfafa2704d27250a7914c9ff

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-formula                  # [build_platform != target_platform]
    - r-inum                     # [build_platform != target_platform]
    - r-libcoin                  # [build_platform != target_platform]
    - r-mvtnorm                  # [build_platform != target_platform]
    - r-party                    # [build_platform != target_platform]
    - r-rpart                    # [build_platform != target_platform]
    - r-survival                 # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-formula >=1.2_1
    - r-inum >=1.0_0
    - r-libcoin >=1.0_0
    - r-mvtnorm
    - r-party >=1.3_0
    - r-rpart >=4.1_11
    - r-survival
  run:
    - r-base
    - r-formula >=1.2_1
    - r-inum >=1.0_0
    - r-libcoin >=1.0_0
    - r-mvtnorm
    - r-party >=1.3_0
    - r-rpart >=4.1_11
    - r-survival

test:
  commands:
    - $R -e "library('partykit')"           # [not win]
    - "\"%R%\" -e \"library('partykit')\""  # [win]

about:
  home: http://partykit.R-Forge.R-project.org/partykit
  license: GPL-2.0-or-later
  summary: A toolkit with infrastructure for representing, summarizing, and visualizing tree-structured regression and classification models. This unified infrastructure can be used for reading/coercing tree models from different sources ('rpart', 'RWeka', 'PMML') yielding objects that share functionality for print()/plot()/predict()
    methods. Furthermore, new and improved reimplementations of conditional inference trees (ctree()) and model-based recursive partitioning (mob()) from the 'party' package are provided based on the new infrastructure. A description of this package was published by Hothorn and Zeileis (2015) <http://jmlr.org/papers/v16/hothorn15a.html>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
