{% set version = '1.2-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-partykit
  version: {{ version|replace("-", "_") }}

source:
  fn: partykit_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/partykit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/partykit/partykit_{{ version }}.tar.gz
  sha256: 6f753f617a9672f0b90d50c40c69631162806a6b28a9cae20370960092cb1f85

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-formula >=1.2_1
    - r-inum >=1.0_0
    - r-libcoin >=1.0_0
    - r-mvtnorm
    - r-rpart >=4.1_11
    - r-survival
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-formula >=1.2_1
    - r-inum >=1.0_0
    - r-libcoin >=1.0_0
    - r-mvtnorm
    - r-rpart >=4.1_11
    - r-survival

test:
  commands:
    - $R -e "library('partykit')"           # [not win]
    - "\"%R%\" -e \"library('partykit')\""  # [win]

about:
  home: http://partykit.R-Forge.R-project.org/partykit
  license: GPL-2 | GPL-3
  summary: A toolkit with infrastructure for representing, summarizing, and visualizing tree-structured
    regression and classification models. This unified infrastructure can be used for
    reading/coercing tree models from different sources ('rpart', 'RWeka', 'PMML') yielding
    objects that share functionality for print()/plot()/predict() methods. Furthermore,
    new and improved reimplementations of conditional inference trees (ctree()) and
    model-based recursive partitioning (mob()) from the 'party' package are provided
    based on the new infrastructure. A description of this package was published by
    Hothorn and Zeileis (2015) <http://jmlr.org/papers/v16/hothorn15a.html>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
