appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: m1ra3r2HhoQP6weSPR+wn2JwMCbmpo56d5xXK4qS/Ho/08UeiQ1Q6q8xyCY/p5FfNMlsImPVNbFLLlZckQNhHR/OpIwFUpxjcZt4adQLuQ1VBX+eBzAsPBJJrnWbrC8OGOKToLEmFKNpkrwrt7C9I6tfuGWC8C+mavOW3QmWv4mKbVuP4C16Yr+/TsaXJZ/29nUD0IO8ERWMJmv4UXdriHLiP/23QiyR37xqWxhGSkMfSLZDJ2qqrbMHBRFua6eTayzK8PPL6rk2AtQVJsfoDYcabUjNZiwDS5Qu0uYxTr6r+HELXhto8nWvtiDkoL0D2KS+QcufssujOqNUN8ozq72f1Sgq6xviNXafp/KQK88okzuA/f6KhKplNIsEksxWqKrBTzr57CZDXmtx47BA0fOKw1CWasml+SgsTmH7S3C1x4Dx0xJEU7QXR9Vlv/uvQ6zTqqLS7x9lOShKJ9xoFWjSfzwK7aLb+x26XRG8P2GOZ3Y1UMSDYO+HbMxukfO/EbAM/LWtf0DIlYeaImqG5vrCI2feXRs6/uSrztKaT9CQt/2WqPQi189DPxqFkLnhzENK5T+Qj+xQBqdD7Z3TI4k+NZmuUNYsXsF4vS0f2XYZIfdd5M+avXxZlQoVn/vNkhhy+dfd+LfAg89YwXDisYgQE++6ur583y5EaOzd8aA=}
bot:
  automerge: true
